[theme]
primaryColor="#22c55e"            # Verde moderninho (ajuste depois)
backgroundColor="#0b1220"         # Fundo escuro
secondaryBackgroundColor="#111827"# Cards
textColor="#e5e7eb"               # Texto claro
font="sans serif"
